
server:
  port: 4000
  context-path: /tattletale

# DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tattletale
    username: microwise
    password: microwise
    # druid Configuration, url:/terminator/druid/index.html
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.3.115
    port: 5672
    username: guest
    password: guest
    virtual-host: /tattletale

  # 邮件相关配置
  mail:
      host: smtpcloud.sohu.com
      port: 25
      username: postmaster@microwise.sendcloud.org
      password: Y7W32uOpmb8fcP1f

# MyBatis
mybatis:
  type-aliases-package: com.microwise.terminator.sys.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.microwise.tattletale.core.TattletaleMapper
  not-empty: false
  identity: select uuid()
  before: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Flyway
flyway:
  validate-on-migrate: false


swagger:
  enabled: true
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.1.0.RELEASE
  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
  contact:
    name: 李建飞
    url: www.microwise-system.com
    email: li.jianfei@microwise-system.com
  base-package: com.microwise
  base-path: /**
  exclude-path: /error, /ops/**

endpoints:
  enabled: true
  sensitive: false

#设备报警通知人
recipient: bai.weixing@microwise-system.com